#![allow(non_snake_case)]
//! Definition of the proof struct.

use mpc_stark::algebra::scalar::ScalarResult;
use mpc_stark::algebra::stark_curve::StarkPointResult;

use crate::errors::MultiproverError;
use crate::r1cs::R1CSProof;

use super::mpc_inner_product::SharedInnerProductProof;

/// A proof generated by a distributed prover; i.e. across multiple machines participating
/// in a multiparty computation.
///
/// The proof is partially shared, as many of the values are opened during protocol execution
/// to keep the transcript consistent between the parties in a simple manner
#[derive(Clone, Debug)]
#[allow(non_snake_case)]
pub struct PartiallySharedR1CSProof {
    /// Commitment to the values of input wires in the first phase.
    pub(super) A_I1: StarkPointResult,
    /// Commitment to the values of output wires in the first phase.
    pub(super) A_O1: StarkPointResult,
    /// Commitment to the blinding factors in the first phase.
    pub(super) S1: StarkPointResult,
    /// Commitment to the values of input wires in the second phase.
    pub(super) A_I2: StarkPointResult,
    /// Commitment to the values of output wires in the second phase.
    pub(super) A_O2: StarkPointResult,
    /// Commitment to the blinding factors in the second phase.
    pub(super) S2: StarkPointResult,
    /// Commitment to the \\(t_1\\) coefficient of \\( t(x) \\)
    pub(super) T_1: StarkPointResult,
    /// Commitment to the \\(t_3\\) coefficient of \\( t(x) \\)
    pub(super) T_3: StarkPointResult,
    /// Commitment to the \\(t_4\\) coefficient of \\( t(x) \\)
    pub(super) T_4: StarkPointResult,
    /// Commitment to the \\(t_5\\) coefficient of \\( t(x) \\)
    pub(super) T_5: StarkPointResult,
    /// Commitment to the \\(t_6\\) coefficient of \\( t(x) \\)
    pub(super) T_6: StarkPointResult,
    /// Evaluation of the polynomial \\(t(x)\\) at the challenge point \\(x\\)
    pub(super) t_x: ScalarResult,
    /// Blinding factor for the synthetic commitment to \\( t(x) \\)
    pub(super) t_x_blinding: ScalarResult,
    /// Blinding factor for the synthetic commitment to the
    /// inner-product arguments
    pub(super) e_blinding: ScalarResult,
    /// Proof data for the inner-product argument.
    /// Made public for integration tests to test malleability
    #[cfg(not(feature = "integration_test"))]
    pub(super) ipp_proof: SharedInnerProductProof,
    #[cfg(feature = "integration_test")]
    pub ipp_proof: SharedInnerProductProof,
}

impl PartiallySharedR1CSProof {
    /// Opens the proof, generating a standard R1CS Proof
    pub async fn open(&self) -> Result<R1CSProof, MultiproverError> {
        // To open, only the inner product proof must be opened
        // Every other value is opened during the course of proof generation to maintain
        // a consistent Merlin transcript
        let ipp_open = self.ipp_proof.open().await?;

        Ok(R1CSProof {
            A_I1: self.A_I1.clone().await,
            A_O1: self.A_O1.clone().await,
            S1: self.S1.clone().await,
            A_I2: self.A_I2.clone().await,
            A_O2: self.A_O2.clone().await,
            S2: self.S2.clone().await,
            T_1: self.T_1.clone().await,
            T_3: self.T_3.clone().await,
            T_4: self.T_4.clone().await,
            T_5: self.T_5.clone().await,
            T_6: self.T_6.clone().await,
            t_x: self.t_x.clone().await,
            t_x_blinding: self.t_x_blinding.clone().await,
            e_blinding: self.e_blinding.clone().await,
            ipp_proof: ipp_open,
        })
    }
}
